# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNWirecard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNWirecard
  pod 'paymentSDK/All', '~>3.6.0'
  pod 'React'
end
